spring.application.name=chatopapi
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.port=3001

jwt.secret=${SECRET_KEY}
jwt.expiration-ms=3600000

app.images.dossier=uploads
app.base-url=http://localhost:3001
